---
# This is grafana definition File that is used for ansible and terraform to generate all required to deploy this. 

grafana_folders: 
  - Docker_Infra
  - Monitoring_Infra

grafana_dashboards: 
  Docker_Infra:
    - dashboard_file: "Docker-Host-Overview.json"
      grafana_datastore: "influxdb-metricstore"
  Monitoring_Infra:
    - dashboard_file: "InfluxDB-Stats-Internal.json"
      grafana_datastore: "influxdb-internal"
